import type { IsoBuilderItem } from '@/components/ui'

/* O catálogo do jogo da cidade: o jogo da carteira e o sandbox do estúdio
   do jogo (`tools/`) leem o mesmo. O preço sai do volume de cada peça, em
   `economy.ts`, para que um item novo não tenha preço inventado à mão; um
   `price` na linha fixa o preço daquela peça.

   O estúdio do jogo grava este arquivo — categoria, subcategoria e preço —
   linha a linha (`tools/server/catalog-file.ts`): cada peça fica numa linha
   só, com `id` primeiro. */
export const CITY_CATALOG: IsoBuilderItem[] = [
  { id: 'suburban-block', label: 'Casas de subúrbio', group: 'Residencial', subgroup: 'Casas', recipe: 'suburbanBlock' },
  { id: 'slate-cottages', label: 'Casas de ardósia', group: 'Residencial', subgroup: 'Casas', recipe: 'slateCottages' },
  { id: 'terracotta-homes', label: 'Casas de terracota', group: 'Residencial', subgroup: 'Casas', recipe: 'terracottaHomes' },
  { id: 'garden-bungalows', label: 'Casas térreas com jardim', group: 'Residencial', subgroup: 'Casas', recipe: 'gardenBungalows' },
  { id: 'leafy-suburb', label: 'Subúrbio arborizado', group: 'Residencial', subgroup: 'Casas', recipe: 'leafySuburb' },
  { id: 'cream-cottages', label: 'Casas de tons claros', group: 'Residencial', subgroup: 'Casas', recipe: 'creamCottages' },
  { id: 'row-house-block', label: 'Quarteirão de sobrados', group: 'Residencial', subgroup: 'Casas', recipe: 'rowHouseBlock' },
  { id: 'brick-terraces', label: 'Sobrados de tijolo', group: 'Residencial', subgroup: 'Casas', recipe: 'brickTerraces' },
  { id: 'garden-villas', label: 'Vilas com jardins', group: 'Residencial', subgroup: 'Casas', recipe: 'gardenVillas' },
  { id: 'terracotta-villas', label: 'Vilas em lotes amplos', group: 'Residencial', subgroup: 'Casas', recipe: 'terracottaVillas' },
  { id: 'quiet-suburb', label: 'Bairro de casas térreas', group: 'Residencial', subgroup: 'Casas', recipe: 'quietSuburb' },
  { id: 'mixed-block', label: 'Casas e sobrados', group: 'Residencial', subgroup: 'Casas', recipe: 'mixedBlock' },
  { id: 'row-houses', label: 'Três sobrados', group: 'Residencial', subgroup: 'Casas', recipe: 'rowHouses' },
  { id: 'small-garden-flats', label: 'Apartamentos com jardim', group: 'Residencial', subgroup: 'Prédios pequenos', recipe: 'smallGardenFlats' },
  { id: 'small-courtyard', label: 'Pátio residencial', group: 'Residencial', subgroup: 'Prédios pequenos', recipe: 'smallCourtyard' },
  { id: 'small-brick-flats', label: 'Blocos de quatro andares', group: 'Residencial', subgroup: 'Prédios pequenos', recipe: 'smallBrickFlats' },
  { id: 'medium-brick-court', label: 'Pátio de tijolo', group: 'Residencial', subgroup: 'Prédios médios', recipe: 'mediumBrickCourt' },
  { id: 'medium-garden-flats', label: 'Alamedas residenciais', group: 'Residencial', subgroup: 'Prédios médios', recipe: 'mediumGardenFlats' },
  { id: 'medium-estate', label: 'Conjunto com jardins', group: 'Residencial', subgroup: 'Prédios médios', recipe: 'mediumEstate' },
  { id: 'large-garden-estate', label: 'Parque residencial', group: 'Residencial', subgroup: 'Prédios grandes', recipe: 'largeGardenEstate' },
  { id: 'large-brick-court', label: 'Grande pátio residencial', group: 'Residencial', subgroup: 'Prédios grandes', recipe: 'largeBrickCourt' },
  { id: 'large-garden-slabs', label: 'Blocos com alameda', group: 'Residencial', subgroup: 'Prédios grandes', recipe: 'largeGardenSlabs' },
  { id: 'glass-tower', label: 'Torre de vidro', group: 'Prédios', subgroup: 'Torres', recipe: 'glassTower' },
  { id: 'brick-tower', label: 'Torre de tijolo', group: 'Prédios', subgroup: 'Torres', recipe: 'brickTower' },
  { id: 'art-deco', label: 'Art déco', group: 'Prédios', subgroup: 'Torres', recipe: 'artDeco' },
  { id: 'turned-tower', label: 'Torre girada', group: 'Prédios', subgroup: 'Torres', recipe: 'turnedTower' },
  { id: 'round-tower', label: 'Torre redonda', group: 'Prédios', subgroup: 'Torres', recipe: 'roundTower' },
  { id: 'terrace-tower', label: 'Torre com terraço', group: 'Prédios', subgroup: 'Torres', recipe: 'terraceTower' },
  { id: 'stepped-slate-tower', label: 'Torre cinza escalonada', group: 'Prédios', subgroup: 'Torres', recipe: 'steppedSlateTower' },
  { id: 'framed-office-tower', label: 'Torre de moldura bege', group: 'Prédios', subgroup: 'Torres', recipe: 'framedOfficeTower' },
  { id: 'limestone-setback-tower', label: 'Torre de pedra em degraus', group: 'Prédios', subgroup: 'Torres', recipe: 'limestoneSetbackTower' },
  { id: 'ribbed-office-tower', label: 'Torre de nervuras', group: 'Prédios', subgroup: 'Torres', recipe: 'ribbedOfficeTower' },
  { id: 'rounded-obsidian-tower', label: 'Torre escura arredondada', group: 'Prédios', subgroup: 'Torres', recipe: 'roundedObsidianTower' },
  { id: 'golden-garden-tower', label: 'Torre de jardim dourado', group: 'Prédios', subgroup: 'Torres', recipe: 'goldenGardenTower' },
  { id: 'walk-up', label: 'Prédio com lojas', group: 'Comércio', subgroup: 'Comércio de rua', recipe: 'walkUp' },
  { id: 'copper-mansard-building', label: 'Prédio de cobertura verde', group: 'Prédios', subgroup: 'Edifícios urbanos', recipe: 'copperMansardBuilding' },
  { id: 'terracotta-court-building', label: 'Prédio de terracota', group: 'Prédios', subgroup: 'Edifícios urbanos', recipe: 'terracottaCourtBuilding' },
  { id: 'red-glass-building', label: 'Prédio vermelho e vidro', group: 'Prédios', subgroup: 'Edifícios urbanos', recipe: 'redGlassBuilding' },
  { id: 'brick-slab-building', label: 'Bloco de apartamentos', group: 'Residencial', subgroup: 'Prédios grandes', recipe: 'brickSlabBuilding' },
  { id: 'bronze-bay-building', label: 'Prédio de bronze', group: 'Prédios', subgroup: 'Edifícios urbanos', recipe: 'bronzeBayBuilding' },
  { id: 'rose-corner-building', label: 'Prédio de esquina rosado', group: 'Prédios', subgroup: 'Edifícios urbanos', recipe: 'roseCornerBuilding' },
  { id: 'diner', label: 'Lanchonete', group: 'Comércio', subgroup: 'Comércio de rua', recipe: 'diner' },
  { id: 'city-hall', label: 'Prefeitura', group: 'Marcos', subgroup: 'Edifícios públicos', recipe: 'cityHall' },
  { id: 'church', label: 'Igreja', group: 'Marcos', subgroup: 'Edifícios públicos', recipe: 'church' },
  { id: 'road', label: 'Rua', group: 'Ruas', subgroup: 'Ruas', recipe: 'road', flat: true, drag: true },
  { id: 'crosswalk', label: 'Faixa de pedestres', group: 'Ruas', subgroup: 'Ruas', recipe: 'crosswalk', flat: true },
  { id: 'crossing', label: 'Cruzamento', group: 'Ruas', subgroup: 'Ruas', recipe: 'crossing', flat: true },
  { id: 'avenue', label: 'Avenida', group: 'Ruas', subgroup: 'Avenidas', recipe: 'avenue', flat: true, drag: true },
  { id: 'boulevard', label: 'Avenida com canteiro', group: 'Ruas', subgroup: 'Avenidas', recipe: 'boulevard', drag: true },
  { id: 'avenue-crossing', label: 'Cruzamento de avenidas', group: 'Ruas', subgroup: 'Avenidas', recipe: 'avenueCrossing', flat: true },
  { id: 'sidewalk', label: 'Calçada', group: 'Ruas', subgroup: 'Ruas', recipe: 'sidewalk', flat: true, drag: true },
  { id: 'tree', label: 'Árvore', group: 'Natureza', subgroup: 'Árvores', recipe: 'tree' },
  { id: 'lawn', label: 'Gramado', group: 'Natureza', subgroup: 'Jardins e praças', recipe: 'lawn', flat: true, drag: true },
  { id: 'square', label: 'Praça', group: 'Natureza', subgroup: 'Jardins e praças', recipe: 'square' },
  { id: 'balcony-tower', label: 'Torre de varandas', group: 'Prédios', subgroup: 'Arranha-céus', recipe: 'balconyTower' },
  { id: 'faceted-tower', label: 'One World Trade Center', group: 'Prédios', subgroup: 'Arranha-céus', recipe: 'oneWorldTradeCenter' },
  { id: 'spiral-tower', label: 'Burj Khalifa', group: 'Prédios', subgroup: 'Arranha-céus', recipe: 'burjKhalifa' },
  { id: 'gherkin', label: 'The Gherkin', group: 'Prédios', subgroup: 'Arranha-céus', recipe: 'gherkin' },
  { id: 'empire-state', label: 'Empire State Building', group: 'Prédios', subgroup: 'Arranha-céus', recipe: 'empireState' },
  { id: 'woolworth-building-codex', hidden: true, label: 'Woolworth Building', group: 'Prédios', subgroup: 'Arranha-céus', recipe: 'woolworth' },
  { id: 'woolworth-building', label: 'Woolworth Building', group: 'Prédios', subgroup: 'Arranha-céus', recipe: 'woolworth' },
  { id: 'central-park-tower', label: 'Central Park Tower', group: 'Prédios', subgroup: 'Arranha-céus', recipe: 'centralParkTower' },
  { id: 'taipei-101', label: 'Taipei 101', group: 'Prédios', subgroup: 'Arranha-céus', recipe: 'taipei101' },
  { id: 'linden-tree', label: 'Árvore de copa clara', group: 'Natureza', subgroup: 'Árvores', recipe: 'lindenTree' },
  { id: 'copper-tree', label: 'Árvore de folhas oliva', group: 'Natureza', subgroup: 'Árvores', recipe: 'copperTree' },
  { id: 'cypress-tree', label: 'Cipreste', group: 'Natureza', subgroup: 'Árvores', recipe: 'cypressTree' },
  { id: 'pine-tree', hidden: true, label: 'Árvore de copa', group: 'Natureza', subgroup: 'Árvores', recipe: 'pineTree' },
  { id: 'small-grove', label: 'Pequeno bosque', group: 'Natureza', subgroup: 'Bosques', recipe: 'smallGrove' },
  { id: 'leafy-grove', label: 'Bosque arborizado', group: 'Natureza', subgroup: 'Bosques', recipe: 'leafyGrove' },
  { id: 'dense-forest', label: 'Mata densa', group: 'Natureza', subgroup: 'Bosques', recipe: 'denseForest' },
  { id: 'garden-walk', label: 'Jardim com caminhos', group: 'Natureza', subgroup: 'Jardins e praças', recipe: 'gardenWalk' },
  { id: 'orchard', label: 'Pomar', group: 'Natureza', subgroup: 'Jardins e praças', recipe: 'orchard' },
]
