from app.core.exceptions import NotFoundError
from app.infra.db.unit_of_work import UnitOfWork
from app.modules.ai.domain.commands import CreateAIPromptVersionCommand
from app.modules.ai.domain.entities import AIPromptVersion
from app.modules.ai.domain.prompt_template import assert_placeholders_known
from app.modules.ai.service.handlers import HANDLER_CLASSES


class AIPromptService:
    """Prompt versions, and the guard that makes editing them in a screen safe.

    A prompt lives in the database so its wording can be changed without a
    deploy. The risk that buys is a template naming data the code never
    assembles, which would only surface as a failed generation in front of
    somebody. So a version is checked against the handler's declared context
    keys **before it is stored**: a prompt that would break cannot be saved.
    """

    def __init__(self, uow: UnitOfWork):
        self.uow = uow

    async def list_versions(self, feature_key: str) -> list[AIPromptVersion]:
        async with self.uow as uow:
            feature = await self._feature(uow, feature_key)
            return await uow.ai.list_prompt_versions(feature.id)

    async def context_keys(self, feature_key: str) -> list[str]:
        """What a prompt for this feature may refer to, for the editor to show."""
        handler = HANDLER_CLASSES.get(feature_key)
        if handler is None:
            raise NotFoundError(f'A feature de IA "{feature_key}" não tem handler')
        return sorted(handler.context_keys)

    async def create_version(self, command: CreateAIPromptVersionCommand) -> AIPromptVersion:
        async with self.uow as uow:
            feature = await self._feature(uow, command.feature_key)

            handler = HANDLER_CLASSES.get(feature.key)
            if handler is None:
                raise NotFoundError(f'A feature de IA "{feature.key}" não tem handler')
            assert_placeholders_known(command.template, handler.context_keys)

            version = AIPromptVersion(
                feature_id=feature.id,
                version=await uow.ai.next_prompt_version_number(feature.id),
                system=command.system,
                template=command.template,
                model=command.model,
                temperature=command.temperature,
                max_output_tokens=command.max_output_tokens,
                web_search=command.web_search,
                notes=command.notes,
                is_active=command.activate,
            )
            if command.activate:
                await uow.ai.deactivate_prompt_versions(feature.id)
            await uow.repository.create(AIPromptVersion, [version])
            await uow.commit()
            return version

    async def activate(self, version_id: int) -> AIPromptVersion:
        """Make one version the one that answers.

        Activating retires nothing by deleting it. The artifacts generated by
        the previous version stay in the table under their own version id, and
        stop being found because the read looks for the active one — which is
        also what makes a new version regenerate everything without a job.
        """
        async with self.uow as uow:
            version = await uow.ai.get_prompt_version(version_id)
            if version is None:
                raise NotFoundError('Versão de prompt não encontrada')
            await uow.ai.deactivate_prompt_versions(version.feature_id)
            version.is_active = True
            await uow.commit()
            return version

    @staticmethod
    async def _feature(uow, feature_key: str):
        feature = await uow.ai.get_feature_by_key(feature_key)
        if feature is None:
            raise NotFoundError(f'A feature de IA "{feature_key}" não está cadastrada')
        return feature
